<?php
/**
 * BooksApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Bookstore\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Swagger Book
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 3.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 4.3.1
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace Bookstore\Client;

use \Bookstore\Client\Configuration;
use \Bookstore\Client\ApiException;
use \Bookstore\Client\ObjectSerializer;

/**
 * BooksApiTest Class Doc Comment
 *
 * @category Class
 * @package  Bookstore\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class BooksApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for addBook
     *
     * Creates a new book.
     *
     */
    public function testAddBook()
    {
    }

    /**
     * Test case for deleteBook
     *
     * .
     *
     */
    public function testDeleteBook()
    {
    }

    /**
     * Test case for findBook
     *
     * get book by id.
     *
     */
    public function testFindBook()
    {
    }

    /**
     * Test case for listBook
     *
     * List of books.
     *
     */
    public function testListBook()
    {
    }

    /**
     * Test case for updateBook
     *
     * .
     *
     */
    public function testUpdateBook()
    {
    }
}
